version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ddbEncryptionBenchmark"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-f2u82qplp31q"
s3_prefix = "ddbEncryptionBenchmark"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
